export const GATE_CASES = [
    { script: '', accepted: true },
    { script: '/echo the rule fired', accepted: true },
    { script: '/echo {{user}} fired', accepted: true },
    { script: '/setvar key=fired value=1 | /getvar fired', accepted: true },
    { script: '/setchatvar key=fired value=1', accepted: true },
    { script: '/flushvar mine', accepted: true },
    { script: '/let count 0 | /incvar count', accepted: true },
    { script: '/if left=1 right=1 {: /echo matched :}', accepted: true },
    { script: '/if left={{getvar::a}} right=1 else={: /echo no :} {: /echo yes :}', accepted: true },
    { script: '/while left=1 right=2 guard=off {: /echo spin :}', accepted: true },
    { script: '/times 3 {: /echo again :}', accepted: true },
    { script: '/let x {: /if left=1 right=1 {: /echo deep :} :}', accepted: true },
    { script: '/echo {: /echo later :}', accepted: true },
    { script: '/imagine quiet=true a quiet room', accepted: true },
    { script: '/sd quiet=true a quiet room', accepted: true },
    { script: '/return done', accepted: true },
    { script: '// a note | /echo hi', accepted: true },
    { script: '/echo one\n/echo two', accepted: true },

    { script: '/gen hello', accepted: false, reasonContains: "/gen isn't on the list" },
    { script: '/echo one | /swipe', accepted: false, reasonContains: "/swipe isn't on the list" },
    { script: '/echo one | /imp await=true', accepted: false, reasonContains: "/imp isn't on the list" },
    { script: '/echo one | /delay 60000', accepted: false, reasonContains: "/delay isn't on the list" },
    { script: '/echo one | /wait 60000', accepted: false, reasonContains: "/wait isn't on the list" },
    { script: '/echo one | /summarize', accepted: false, reasonContains: "/summarize isn't on the list" },
    { script: '/echo one | /send injected', accepted: false, reasonContains: "/send isn't on the list" },
    { script: '/let x {: /swipe :}', accepted: false, reasonContains: "/swipe isn't on the list" },
    { script: '/echo {: /trigger :}()', accepted: false, reasonContains: "/trigger isn't on the list" },
    { script: '/notacommand x', accepted: false, reasonContains: "can't read this script" },
    { script: '/ge{{noop}}n hi', accepted: false, reasonContains: "can't read this script" },

    { script: '/if left=1 right=1 rule=eq\n{{lastMessage}}', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/if left=1 right=1 rule=eq\r\n{{lastMessage}}', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/if left=1 right=1 rule=eq\t{{lastMessage}}', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/while left=1 right=2 guard=off\n{{pipe}}', accepted: false, reasonContains: '/while can only run a closure' },
    { script: '/while left=1 right=2 guard=off\r\n{{pipe}}', accepted: false, reasonContains: '/while can only run a closure' },
    { script: '/while left=1 right=2 guard=off\t{{pipe}}', accepted: false, reasonContains: '/while can only run a closure' },
    { script: '/if left=1 right=1\n"{{getvar::x}}"', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/while left=1 right=1\n"{{getvar::x}}"', accepted: false, reasonContains: '/while can only run a closure' },
    { script: '/if left=1 right=2\nelse="{{getvar::x}}" "/echo safe"', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/echo {: /if left=1 right=1\n"{{getvar::x}}" :}()', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/if left=1 right=1 rule=eq "/echo \\" x={{lastMessage}} "', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/if left=1 right=1 "{{getvar::script}}"', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/if left=1 right=1 "/ge{{noop}}n hi"', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/setvar key=c "/ge{{noop}}n hi" | /if left=1 right=1 "{{getvar::c}}"', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/times 2 "/echo hi"', accepted: false, reasonContains: '/times can only run a closure' },
    { script: '/if left=1 right=1 else="/echo no" {: /echo yes :}', accepted: false, reasonContains: '/if can only run a closure' },
    { script: '/echo onClick="/echo later" hi', accepted: false, reasonContains: '/echo can only run a closure' },

    { script: '/getvar x | /if left=1 right=1', accepted: false, reasonContains: '/if has nothing to run' },
    { script: '/getvar x | /while left=1 right=1', accepted: false, reasonContains: '/while has nothing to run' },
    { script: '/getvar x | /times 3', accepted: false, reasonContains: '/times has nothing to run' },

    { script: '/parser-flag STRICT_ESCAPING on | /if left=1 right=1 rule=eq x=\\| {{lastMessage}}', accepted: false, reasonContains: "/parser-flag isn't on the list" },
    { script: '/closure-deserialize {{lastMessage}} | /let c {{pipe}} | /inject id=j filter={{var::c}} x', accepted: false, reasonContains: "/closure-deserialize isn't on the list" },
    { script: '/closure-deserialize {{getvar::x}} | /flushvar', accepted: false, reasonContains: "/closure-deserialize isn't on the list" },
    { script: '/import from=Library.Q foo | /flushvar {{var::foo}}', accepted: false, reasonContains: "/import isn't on the list" },
    { script: '/qr-set-create x | /qr-create set=x label=b bot=true {{lastMessage}}', accepted: false, reasonContains: "/qr-set-create isn't on the list" },
    { script: '/echo one | /run thing', accepted: false, reasonContains: "/run isn't on the list" },
    { script: '/: myQuickReply', accepted: false },
    { script: '/inject id=j filter={: /echo a :} x', accepted: false, reasonContains: "/inject isn't on the list" },

    { script: '/flushvar {{var::c}}', accepted: false, reasonContains: '/flushvar needs a plain variable name' },
    { script: '/flushglobalvar {{pipe}}', accepted: false, reasonContains: '/flushglobalvar needs a plain variable name' },

    { script: '/imagine a quiet room', accepted: false, reasonContains: '/imagine needs quiet=true' },
    { script: '/imagine quiet={{getvar::q}} a quiet room', accepted: false, reasonContains: '/imagine needs quiet=true' },
    { script: '/img a quiet room', accepted: false, reasonContains: '/img needs quiet=true' },
];
