import { DEFAULT_ACTION, NUDGE, REROLL, RUN_SCRIPT } from './actions.js';
import { ALL_CONTEXT, NO_CONTEXT } from './context-groups.js';
import { SCHEMA_VERSION } from './limits.js';
import { CHOICE, NOUL, SCORE, blankLevels, seedCondition } from './sensor-types.js';

export const BUILT_IN = 'Director';

export function blankSensor(id) {
    return {
        id,
        label: '',
        watch: false,
        type: SCORE,
        user: 1,
        assistant: 1,
        context: NO_CONTEXT,
        contextPieces: [],
        repeat: '',
        question: '',
        levels: blankLevels(),
        options: [],
    };
}

export function blankRule(id, sensor) {
    return {
        id,
        label: '',
        enabled: false,
        action: DEFAULT_ACTION,
        conditions: [seedCondition(sensor)],
        need: 3,
        window: 4,
        skipWhen: null,
        cooldown: 0,
        directive: '',
        script: '',
        list: '',
        value: '',
    };
}

const reply = { type: SCORE, user: 1, assistant: 1, context: NO_CONTEXT, contextPieces: [] };
const story = { type: SCORE, user: 0, assistant: 1, context: ALL_CONTEXT, contextPieces: [] };

const expressions = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity',
    'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear',
    'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
    'remorse', 'sadness', 'surprise', 'neutral',
].map(name => ({ name, description: '' }));

const builtInSensors = [
    {
        id: 'change',
        label: 'Change',
        watch: false,
        ...reply,
        question: 'How much does the situation change in `latest_turn`?',
        levels: [
            'Nothing changes. The scene stays as it was.',
            'Small talk or routine activity. The situation is the same at the end.',
            'The scene moves forward a little. Someone learns something, or a minor thing changes.',
            'The situation changes in a way that matters. Someone gains or loses power, makes a real decision, or reveals something important.',
            'A major turning point. The situation at the end is very different from the start.',
        ],
    },
    {
        id: 'tension',
        label: 'Tension',
        watch: false,
        ...reply,
        question: 'How much tension or pressure is in `latest_turn`?',
        levels: [
            'None. Everyone is relaxed and safe.',
            'Mild. Some unease, awkwardness, or anticipation.',
            'Clear. Someone is under pressure, in conflict, or has something to lose.',
            'High. Open confrontation, serious risk, or someone is being forced.',
            'Extreme. Someone faces disaster right now.',
        ],
    },
    {
        id: 'cost',
        label: 'Cost',
        watch: false,
        ...reply,
        question: 'How badly do things go for {{user}} in `latest_turn`?',
        levels: [
            'Things go well for {{user}}, or nothing is at stake.',
            'A minor annoyance or discomfort for {{user}}.',
            'A real setback for {{user}}. {{user}} fails, is refused, or loses ground.',
            'A serious loss or harm for {{user}}.',
            'A disaster for {{user}}.',
        ],
    },
    {
        id: 'speaks',
        label: 'Speaks for you',
        watch: false,
        ...reply,
        question: 'How much does `latest_turn` write what only {{user}} does, says, or thinks?',
        levels: [
            'It writes nothing that {{user}} does, says, or thinks. Describing what {{user}} sees, hears, or feels around them does not count, and neither does another character acting on {{user}}.',
            'It restates only what {{user}} already did or said in `player_message`.',
            'It adds one small reaction or movement for {{user}} that they did not choose.',
            'It writes one new thing that {{user}} chooses to say, think, or do.',
            'It makes decisions for {{user}}, or writes several actions or lines for {{user}}.',
        ],
    },
    {
        id: 'repeats',
        label: 'Repeats',
        watch: false,
        type: SCORE,
        user: 0,
        assistant: 5,
        context: NO_CONTEXT,
        contextPieces: [],
        question: 'How much does `latest_turn` reuse phrases or sentence patterns from `history`?',
        levels: [
            'Nothing is reused.',
            'A few common words return.',
            'One distinctive phrase or image from an earlier reply returns.',
            'Several phrases or the same sentence pattern return.',
            'The reply follows the structure and wording of an earlier reply.',
        ],
    },
    {
        id: 'tone',
        label: 'Tone',
        watch: false,
        ...story,
        question: 'How well do the tone and themes of `latest_turn` match the intent of `context`?',
        levels: [
            'The tone and themes are unrelated to the intent.',
            'Mostly different from the intent.',
            'Partly matches the intent.',
            'Mostly matches the intent.',
            'Fully matches the intended tone and themes.',
        ],
    },
    {
        id: 'world',
        label: 'World',
        watch: false,
        ...story,
        question: 'How much does `latest_turn` build on the world that `context` establishes?',
        levels: [
            'It ignores the world. It could be from a generic story.',
            'It uses only names and places from the world.',
            'It uses some specific rules or elements of the world.',
            'It clearly builds on the specific rules, elements, and premise of the world.',
            'The premise of the world drives what happens.',
        ],
    },
    {
        id: 'scene',
        label: 'Scene',
        watch: false,
        type: CHOICE,
        user: 1,
        assistant: 0,
        context: NO_CONTEXT,
        contextPieces: [],
        question: 'What kind of scene does `player_message` ask for?',
        levels: [],
        options: [
            { name: 'combat', description: 'A fight or a chase, or the player attacks or defends.' },
            { name: 'conversation', description: 'The player talks with someone and wants an answer.' },
            { name: 'travel', description: 'The player moves to another place.' },
            { name: 'intimate', description: 'A close, romantic or tender moment.' },
            { name: 'downtime', description: 'Rest, routine, shopping, or no clear aim.' },
        ],
    },
    {
        id: 'attention',
        label: 'Attention',
        watch: false,
        ...reply,
        question: 'How much does `latest_turn` respond to what {{user}} said or asked in `player_message`?',
        levels: [
            'It does not respond to what {{user}} said or asked.',
            'It responds to part of what {{user}} said or asked.',
            'It responds to what {{user}} said or asked.',
        ],
    },
    {
        id: 'closeness',
        label: 'Closeness',
        watch: false,
        type: SCORE,
        user: 10,
        assistant: 10,
        context: NO_CONTEXT,
        contextPieces: [],
        question: 'How close are {{char}} and {{user}} at the end of `latest_turn`?',
        levels: [
            'Strangers, or pulled back to speaking only about what has to be done.',
            'Guarded and polite, sharing nothing personal now.',
            'Friendly, sharing small personal things.',
            'Trusting, sharing real things, and seeking each other out.',
            'Close, with open affection or open reliance.',
            'Fully bonded and unguarded, acting on the bond at a cost.',
        ],
    },
    {
        id: 'house',
        label: 'House rule',
        watch: false,
        type: NOUL,
        user: 1,
        assistant: 1,
        context: NO_CONTEXT,
        contextPieces: [],
        repeat: 'rules',
        question: '`latest_turn` follows this rule: {{entry}}',
        levels: [],
    },
    {
        id: 'picture_striking',
        label: 'Striking image',
        watch: false,
        ...reply,
        question: 'How striking is the strongest image in `latest_turn`?',
        levels: [
            'There is nothing to look at.',
            'Surroundings are mentioned in passing.',
            'There is a clear image of a place, a person, or an action.',
            'There is one vivid image that a reader would picture at once.',
            'There is one image so vivid that it would make a good picture on its own.',
        ],
    },
    {
        id: 'picture_now',
        label: 'Happening now',
        watch: false,
        type: NOUL,
        user: 1,
        assistant: 1,
        context: NO_CONTEXT,
        contextPieces: [],
        question: 'The strongest image in `latest_turn` is in the scene happening now, and is not remembered, reported second-hand, imagined, or planned.',
        levels: [],
    },
    {
        id: 'mood',
        label: 'Mood',
        watch: false,
        type: CHOICE,
        user: 0,
        assistant: 1,
        context: NO_CONTEXT,
        contextPieces: [],
        question: 'Which emotion does {{char}} show in `latest_turn`?',
        levels: [],
        options: expressions,
    },
];

const builtInRules = [
    {
        id: 'puppet',
        label: 'Puppet',
        enabled: true,
        action: REROLL,
        conditions: [{ sensor: 'speaks', op: 'above', value: 2.85 }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 2,
        directive: '(OOC: The last reply wrote actions, speech, or thoughts for {{user}}. Write only the other characters and the world. Stop where {{user}} must act.)',
        script: '',
    },
    {
        id: 'attention',
        label: 'Attention',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'attention', op: 'below', value: 0.4 }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 2,
        directive: '(OOC: Your last reply did not respond to what {{user}} said. In this reply, respond to it. A refusal is a response.)',
        script: '',
    },
    {
        id: 'echo',
        label: 'Echo',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'repeats', op: 'above', value: 3 }],
        need: 4,
        window: 6,
        skipWhen: null,
        cooldown: 6,
        directive: '(OOC: Recent replies reuse the same phrases and sentence patterns. In this reply, use new wording and a different structure.)',
        script: '',
    },
    {
        id: 'drift',
        label: 'Drift',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'tone', op: 'below', value: 1.5 }],
        need: 5,
        window: 5,
        skipWhen: { sensor: 'tension', op: 'above', value: 2.5 },
        cooldown: 5,
        directive: '(OOC: The tone and themes of the story have drifted from the initial intent of the instructions at the beginning of the prompt. Recalibrate in your next reply.)',
        script: '',
    },
    {
        id: 'gentle',
        label: 'Gentle',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'cost', op: 'below', value: 1.0 }],
        need: 18,
        window: 20,
        skipWhen: null,
        cooldown: 20,
        directive: '(OOC: Things have gone {{user}}\'s way for a long time. In this reply, let something go against {{user}}. How is your choice. Do not resolve it in this reply.)',
        script: '',
    },
    {
        id: 'scene_combat',
        label: 'Scene: combat',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'scene', op: 'is', value: 'combat' }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 0,
        directive: '(OOC: Write this reply as short, fast beats. One exchange only. Do not end the fight in this reply.)',
        script: '',
    },
    {
        id: 'scene_conversation',
        label: 'Scene: conversation',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'scene', op: 'is', value: 'conversation' }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 0,
        directive: "(OOC: Keep the scene where it is. Write the other character's answer and small actions. Add no new event.)",
        script: '',
    },
    {
        id: 'scene_travel',
        label: 'Scene: travel',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'scene', op: 'is', value: 'travel' }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 0,
        directive: '(OOC: Pass over the journey in a few lines. Stop at the first moment that needs a decision from {{user}}.)',
        script: '',
    },
    {
        id: 'scene_intimate',
        label: 'Scene: intimate',
        enabled: true,
        action: NUDGE,
        conditions: [{ sensor: 'scene', op: 'is', value: 'intimate' }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 0,
        directive: '(OOC: Stay in this moment. Do not skip ahead and do not end the scene in this reply.)',
        script: '',
    },
    {
        id: 'flat',
        label: 'Flat',
        enabled: false,
        action: NUDGE,
        conditions: [
            { sensor: 'change', op: 'below', value: 2.5 },
            { sensor: 'tension', op: 'below', value: 1.5 },
        ],
        need: 3,
        window: 4,
        skipWhen: null,
        cooldown: 4,
        directive: '(OOC: The story has been calm for many turns. In this reply, something puts {{user}} under pressure or tension. How is your choice. Do not resolve it in this reply.)',
        script: '',
    },
    {
        id: 'lore',
        label: 'Lore',
        enabled: false,
        action: REROLL,
        conditions: [{ sensor: 'world', op: 'below', value: 2 }],
        need: 5,
        window: 5,
        skipWhen: null,
        cooldown: 0,
        directive: '(OOC: The story has stopped using the established world and its rules. In this reply, make the rules and premise of the world matter.)',
        script: '',
    },
    {
        id: 'house',
        label: 'House rule',
        enabled: true,
        action: REROLL,
        conditions: [{ sensor: 'house', op: 'below', value: 0.5 }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 2,
        directive: '(OOC: Your last reply broke a rule. Rewrite it and follow:\n{{entries}})',
        script: '',
    },
    {
        id: 'picture',
        label: 'Picture',
        enabled: false,
        action: RUN_SCRIPT,
        conditions: [
            { sensor: 'picture_striking', op: 'above', value: 3.6 },
            { sensor: 'picture_now', op: 'above', value: 0.5 },
        ],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 4,
        directive: '',
        script: '/imagine scene',
    },
    {
        id: 'mood',
        label: 'Mood',
        enabled: false,
        action: RUN_SCRIPT,
        conditions: [{ sensor: 'mood', op: 'is_not', value: 'neutral' }],
        need: 1,
        window: 1,
        skipWhen: null,
        cooldown: 0,
        directive: '',
        script: '/expression-set {{jeved::mood}}',
    },
];

export const builtInPresets = {
    [BUILT_IN]: {
        jeved: SCHEMA_VERSION,
        description: 'Puppet rerolls a reply that writes your character. House rule rerolls a reply that breaks one of the house rules you keep in the "rules" list, and makes no call while that list is empty. Attention, Echo, Drift and Gentle add one line to your next message when they fire. The four Scene rules read your message before the reply and steer that same reply. Four rules are off: Flat, Lore, Picture and Mood. Picture needs an image backend and Mood needs character sprites. Closeness only measures; tick "Measure anyway" to chart it.',
        lists: [{ name: 'rules', entries: [] }],
        sensors: builtInSensors,
        rules: builtInRules,
    },
};

export function builtInPreset(name = BUILT_IN) {
    return builtInPresets[name] ? structuredClone(builtInPresets[name]) : null;
}
